export const CHARACTERS = [
  {
    id: 'jaszy',
    name: 'Jaszy',
    sprites: {
      select: '/assets/characters/character-jaszy/idle.png',
      idle: '/assets/characters/character-jaszy/idle.png',
      walkLeft: '/assets/characters/character-jaszy/walk-left.png',
      walkRight: '/assets/characters/character-jaszy/walk-right.png',
      jump: '/assets/characters/character-jaszy/jump.png',
      crouch: '/assets/characters/character-jaszy/crouch.png',
      back: '/assets/characters/character-jaszy/back.png',
    },
    fallback: {
      color: '#61d7ed',
      shape: 'circle',
    },
  },
  {
    id: 'maikel',
    name: 'Maikel',
    sprites: {
      select: '/assets/characters/character-maikel/idle.png',
      idle: '/assets/characters/character-maikel/idle.png',
      walkLeft: '/assets/characters/character-maikel/walk-left.png',
      walkRight: '/assets/characters/character-maikel/walk-right.png',
      jump: '/assets/characters/character-maikel/jump.png',
      crouch: '/assets/characters/character-maikel/crouch.png',
      back: '/assets/characters/character-maikel/back.png',
    },
    fallback: {
      color: '#ffbb69',
      shape: 'square',
    },
  },
  {
    id: 'max',
    name: 'Max',
    sprites: {
      select: '/assets/characters/character-max/idle.png',
      idle: '/assets/characters/character-max/idle.png',
      walkLeft: '/assets/characters/character-max/walk-left.png',
      walkRight: '/assets/characters/character-max/walk-right.png',
      jump: '/assets/characters/character-max/jump.png',
      crouch: '/assets/characters/character-max/crouch.png',
      back: '/assets/characters/character-max/back.png',
    },
    fallback: {
      color: '#c39aff',
      shape: 'diamond',
    },
  },
  {
    id: 'lucas',
    name: 'Lucas',
    sprites: {
      select: '/assets/characters/character-lucas/idle.png',
      idle: '/assets/characters/character-lucas/idle.png',
      walkLeft: '/assets/characters/character-lucas/walk-left.png',
      walkRight: '/assets/characters/character-lucas/walk-right.png',
      jump: '/assets/characters/character-lucas/jump.png',
      crouch: '/assets/characters/character-lucas/crouch.png',
      back: '/assets/characters/character-lucas/back.png',
    },
    fallback: {
      color: '#f18fba',
      shape: 'triangle',
    },
  },
  {
    id: 'tim',
    name: 'Tim',
    sprites: {
      select: '/assets/characters/character-tim/idle.png',
      idle: '/assets/characters/character-tim/idle.png',
      walkLeft: '/assets/characters/character-tim/walk-left.png',
      walkRight: '/assets/characters/character-tim/walk-right.png',
      jump: '/assets/characters/character-tim/jump.png',
      crouch: '/assets/characters/character-tim/crouch.png',
      back: '/assets/characters/character-tim/back.png',
    },
    fallback: {
      color: '#83df94',
      shape: 'circle',
    },
  },
  {
    id: 'koen',
    name: 'Koen',
    sprites: {
      select: '/assets/characters/character-koen/idle.png',
      idle: '/assets/characters/character-koen/idle.png',
      walkLeft: '/assets/characters/character-koen/walk-left.png',
      walkRight: '/assets/characters/character-koen/walk-right.png',
      jump: '/assets/characters/character-koen/jump.png',
      crouch: '/assets/characters/character-koen/crouch.png',
      back: '/assets/characters/character-koen/back.png',
    },
    fallback: {
      color: '#f5df70',
      shape: 'square',
    },
  },
  {
    id: 'enes',
    name: 'Enes',
    sprites: {
      select: '/assets/characters/character-enes/idle.png',
      idle: '/assets/characters/character-enes/idle.png',
      walkLeft: '/assets/characters/character-enes/walk-left.png',
      walkRight: '/assets/characters/character-enes/walk-right.png',
      jump: '/assets/characters/character-enes/jump.png',
      crouch: '/assets/characters/character-enes/crouch.png',
      back: '/assets/characters/character-enes/back.png',
    },
    fallback: {
      color: '#779bff',
      shape: 'diamond',
    },
  },
];
